apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://master.cloud.com:443
    certificate-authority: /export/kubecertificate/certs/ca.crt
users:
- name: kubelet
  user:
    client-certificate: /export/kubecertificate/certs/server.crt
    client-key: /export/kubecertificate/certs/server.key
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
