apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      hostname: ldap
      containers:
      - name: ldap-container
        image: master.cloud.com:5000/ldap
        ports:
        - name: ldap-port
          containerPort: 8181
        - name: search-port
          containerPort: 389
        - name: ssl-port
          containerPort: 636
        - name: ssh-port
          containerPort: 22
        - name: ssh-port2
          containerPort: 2122
        env:
        - name: LDAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldapsecret
              key: password
        - name: KERB_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: krbsecret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  clusterIP: None
  ports:
  - port: 8181
    protocol: TCP
    name: ldap
  - port: 389
    protocol: TCP
    name: search
  - port: 22
    protocol: TCP
    name: ssh-port
  - port: 2122
    protocol: TCP
    name: ssh-port2
  - port: 636
    protocol: TCP
    name: ssl-tcp
  - port: 636
    protocol: UDP
    name: ssl-udp
  selector:
    app: ldap

